import {
  mdiAccountMultiple,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiBookOpenPageVariant,
  mdiChatAlert,
  mdiCog,
  mdiCrown,
  mdiCrownOutline,
  mdiDice1,
  mdiDice2,
  mdiDice3,
  mdiDice4,
  mdiDice5,
  mdiHistory,
  mdiHome,
  mdiInformation,
  mdiLockOpen,
  mdiMapSearch,
  mdiMusic,
  mdiMusicOff,
  mdiSwapVertical,
  mdiVolumeHigh,
} from '@mdi/js'
const aliases: {
  [name: string]: string
}
 = {
  casts: mdiAccountMultiple,
  conditions: mdiLockOpen,
  home: mdiHome,
  inbound: mdiArrowUp,
  introduction: mdiInformation,
  left: mdiArrowLeft,
  level1: mdiDice1,
  level2: mdiDice2,
  level3: mdiDice3,
  level4: mdiDice4,
  level5: mdiDice5,
  moves: mdiHistory,
  mute: mdiMusicOff,
  outbound: mdiArrowDown,
  right: mdiArrowRight,
  settings: mdiCog,
  scoreEmpty: mdiCrownOutline,
  scoreFull: mdiCrown,
  solve: mdiMapSearch,
  sound: mdiMusic,
  story: mdiBookOpenPageVariant,
  transportation: mdiSwapVertical,
  tips: mdiChatAlert,
  volume: mdiVolumeHigh,
}

export default aliases
