/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HomeListContainer: typeof import('./components/home/HomeListContainer.vue')['default']
    HomeListItem: typeof import('./components/home/HomeListItem.vue')['default']
    HomeListScoreRating: typeof import('./components/home/HomeListScoreRating.vue')['default']
    HomeRecordsScore: typeof import('./components/home/HomeRecordsScore.vue')['default']
    PortraitMenu: typeof import('./components/navigation/PortraitMenu.vue')['default']
    PortraitToolbar: typeof import('./components/navigation/PortraitToolbar.vue')['default']
    PuzzleCarrier: typeof import('./components/objects/PuzzleCarrier.vue')['default']
    PuzzleCarrierMenu: typeof import('./components/objects/carrier/PuzzleCarrierMenu.vue')['default']
    PuzzleCarrierTooltip: typeof import('./components/objects/carrier/PuzzleCarrierTooltip.vue')['default']
    PuzzleCast: typeof import('./components/objects/PuzzleCast.vue')['default']
    PuzzleCastAvatar: typeof import('./components/objects/cast/PuzzleCastAvatar.vue')['default']
    PuzzleCastEmotion: typeof import('./components/objects/cast/PuzzleCastEmotion.vue')['default']
    PuzzleCastMenu: typeof import('./components/objects/cast/PuzzleCastMenu.vue')['default']
    PuzzleCastNameplate: typeof import('./components/objects/cast/PuzzleCastNameplate.vue')['default']
    PuzzleStage: typeof import('./components/PuzzleStage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneNavigation: typeof import('./components/navigation/SceneNavigation.vue')['default']
    SceneNavigationCasts: typeof import('./components/navigation/SceneNavigationCasts.vue')['default']
    SceneNavigationRules: typeof import('./components/navigation/SceneNavigationRules.vue')['default']
    SceneResultDialog: typeof import('./components/navigation/SceneResultDialog.vue')['default']
    SceneSoundAndSplash: typeof import('./components/navigation/SceneSoundAndSplash.vue')['default']
    SceneToolbar: typeof import('./components/navigation/SceneToolbar.vue')['default']
    SceneToolbarMoves: typeof import('./components/navigation/SceneToolbarMoves.vue')['default']
    SceneToolbarNavigation: typeof import('./components/navigation/SceneToolbarNavigation.vue')['default']
    SceneToolbarSolve: typeof import('./components/navigation/SceneToolbarSolve.vue')['default']
    SettingsMenu: typeof import('./components/navigation/SettingsMenu.vue')['default']
  }
}
