/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ListContainer: typeof import('./components/home/ListContainer.vue')['default']
    ListItem: typeof import('./components/home/ListItem.vue')['default']
    PortraitFooter: typeof import('./components/navigation/PortraitFooter.vue')['default']
    PortraitMenu: typeof import('./components/navigation/PortraitMenu.vue')['default']
    PortraitToolbar: typeof import('./components/navigation/PortraitToolbar.vue')['default']
    PuzzleCarrier: typeof import('./components/objects/PuzzleCarrier.vue')['default']
    PuzzleCarrierMenu: typeof import('./components/objects/carrier/PuzzleCarrierMenu.vue')['default']
    PuzzleCarrierTooltip: typeof import('./components/objects/carrier/PuzzleCarrierTooltip.vue')['default']
    PuzzleCast: typeof import('./components/objects/PuzzleCast.vue')['default']
    PuzzleCastAvatar: typeof import('./components/objects/cast/PuzzleCastAvatar.vue')['default']
    PuzzleCastEmotion: typeof import('./components/objects/cast/PuzzleCastEmotion.vue')['default']
    PuzzleCastMenu: typeof import('./components/objects/cast/PuzzleCastMenu.vue')['default']
    PuzzleCastNameplate: typeof import('./components/objects/cast/PuzzleCastNameplate.vue')['default']
    RecordsScore: typeof import('./components/home/RecordsScore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneMoves: typeof import('./components/navigation/SceneMoves.vue')['default']
    SceneNavigation: typeof import('./components/navigation/SceneNavigation.vue')['default']
    SceneNavigationCasts: typeof import('./components/navigation/SceneNavigationCasts.vue')['default']
    SceneNavigationRules: typeof import('./components/navigation/SceneNavigationRules.vue')['default']
    SceneResultDialog: typeof import('./components/navigation/SceneResultDialog.vue')['default']
    SceneSoundAndSplash: typeof import('./components/navigation/SceneSoundAndSplash.vue')['default']
    SceneStage: typeof import('./components/navigation/SceneStage.vue')['default']
    SceneToolbar: typeof import('./components/navigation/SceneToolbar.vue')['default']
    SceneToolbarMoves: typeof import('./components/navigation/SceneToolbarMoves.vue')['default']
    SceneToolbarNavigation: typeof import('./components/navigation/SceneToolbarNavigation.vue')['default']
    SceneToolbarSolve: typeof import('./components/navigation/SceneToolbarSolve.vue')['default']
    ScoreRating: typeof import('./components/home/ScoreRating.vue')['default']
    SettingsMenu: typeof import('./components/navigation/SettingsMenu.vue')['default']
  }
}
